[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-06/=lib/openzeppelin-contracts-06/",
]

# eth_rpc_url = 'https://eth-sepolia.g.alchemy.com/v2/Z5P-u_qrY_2w3AgnOJOiA'
eth_rpc_url = 'https://arb-sepolia.g.alchemy.com/v2/Z5P-u_qrY_2w3AgnOJOiA'
etherscan_api_key = '${ETHERSCAN_KEY}'